all: status

status:
	git status

pdf:
	pdflatex latexorg.tex
	pdflatex comma0mu-semicolonnat-colonnat.tex
	pdflatex comma10mu-semicolon20mu-colon30mu.tex
	pdflatex comma5pt-semicolon5pt-colon5pt.tex
	lualatex mathpunctspace.tex
